### ISSUE TITLE
About error messages in 'for-pairs'

### ISSUE THREAD

**Issue by hakdir** [SquidDev/urn#18]
(for-pairs vars tbl &body)
Macro defined at lib/core/base.lisp:352:2

It seems like the existance if the 'tbl' element is not properly checked. It should fail if a variable that should represent 'tbl' is missing. Instead there is a bad argument error.

In the repl this works:
~~~~~~~~~~~~~
urn
> (for-pairs (k v ) gg (print! k))
[ERROR] Cannot find variable 'gg'
  => <stdin>:[1:19 .. 1:20]
 1 │ (for-pairs (k v ) gg (print! k)
~~~~~~~~~~~~~

But not in the script.
~~~~~~~~~~~~~~~~~~~~~~~~~
 cat test.urn 
(define xx (lambda (ll) 
   (let ((res ll)
         (mystruct (struct-literal :foo 123)))
     (for-pairs
       (k v)
       struct
       (push! res (list k v))
       res))))

(xx (list))

Error:
lua: out.lua:92: bad argument #1 to 'next1' (table expected, got function)
stack traceback:
        [C]: in function 'next1'
        out.lua:92: in function <out.lua:90>
        (...tail calls...)
        [C]: in ?

**Comment by SquidDev** [comment]
The issue here is that [`struct` _does_ exist](http://urn-lang.com/docs/lib.core.table.html#struct-entries), it's just not a table. Urn doesn't currently catch type errors like this at compile time, as working out types is rather difficult.

I've been working for a bit on something which would be able to detect these sorts of errors, but it's a long way from being usable. Sorry.
